name = "SMW Level 01"
x = 50
y = 11

[Level]
....................MMMM.........M............MMMM
..................................................
............M.................M.........M.........
..................M......M........................
........M...................K.C...................
......1.......M.........RRRRRRRRRRM...MMM.........
......M.................DDDDDDDDDD.M..............
..................RRRRRRDDDDDDDDDD..M.............
MS..K...SM.G.K..C.DDDDDDDDDDDDDDDD...M............
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
[/Level]