name = "SMW Level 01"
x = 50
y = 11

[Level]
....................MMMM.........M............MMMM
..................................................
............M.................M.........M.........
..................M......M........................
........M.....................C...................
......1.......M.........RRRRRRRRRRM...MMM.........
......M.................DDDDDDDDDD.M..............
..................RRRRRRDDDDDDDDDD..M.............
MS......SM.G....C.DDDDDDDDDDDDDDDD...M............
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
[/Level]