name = "SMW Level 01"
x = 50
y = 15

[Level]
............M.....................MM..............
..................................................
...............................cccccccc...........
..........LLLLL................LLLLLLLL...........
....................LLLL......................LLLL
..................................................
...c........U.................M.........M.........
..................M......M........................
........UU..............c.cKc.c.c.c...............
......1.......M.........RRRRRRRRRRU...MMM...cccc..
......H.................DDDDDDDDDD.U..............
..................RRRRRRDDDDDDDDDD..U.............
OS..KC..SO.G....C.DDDDDDDDDDDDDDDD...O.....K.....O
RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR
DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD
[/Level]